name: API Node.js CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:    
    - name: Setup MySQL Image
      uses: mirromutth/mysql-action@v1.1
      with:
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mysql database: 'mer'
        mysql root password: 'teste'
    
    #- name: Build Local API Dev Docker Image
    #  run: docker build -t apidev:latest -f dev.Dockerfile .
    
    - name: Checkout API Project
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install --also=dev
      working-directory: src

    - name: Database Migration
      run: npx sequelize-cli db:migrate
      working-directory: src

    - name: Database Seed
      run: npx sequelize-cli db:seed:all
      working-directory: src

    #- name: Runnning build
    #  run: npm run build --if-present

    - name: Running tests
      run: npm test
      working-directory: src
      env:
        CI: true

    - name: Dump docker logs on failure
      if: failure()
      uses: jwalton/gh-docker-logs@v1